# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_auto_20171114_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='user_id',
        ),
    ]
