# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_auto_20171114_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permissions',
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='user_management.Group'),
        ),
    ]
