# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_auto_20171114_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='roles',
            field=models.ManyToManyField(null=True, to='user_management.Role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(null=True, to='user_management.Permission'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.ForeignKey(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.Group'),
        ),
    ]
