# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_auto_20171114_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='null', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(auto_created=True, null=True, to='user_management.Permission'),
        ),
    ]
