# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_auto_20171114_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='roles',
        ),
        migrations.AddField(
            model_name='group',
            name='roles',
            field=models.ManyToManyField(auto_created=True, null=True, to='user_management.Role'),
        ),
    ]
