# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_auto_20171114_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='roles',
            field=models.ManyToManyField(auto_created=True, to='user_management.Role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(auto_created=True, to='user_management.Permission'),
        ),
    ]
