# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_auto_20171114_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permissions',
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(auto_created=True, to='user_management.Group'),
        ),
    ]
