# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_auto_20171114_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='display_name',
        ),
    ]
